FROM maven:3.9-eclipse-temurin-21 AS builder

ARG MVN_PROFILE=""

COPY . /build

WORKDIR /build

RUN --mount=type=cache,target=/root/.m2 mvn clean install ${MVN_PROFILE}

RUN mkdir target/layers \
    && cp target/exchange-rates-sample-*.jar target/layers

WORKDIR /build/target/layers

RUN java -Djarmode=layertools -jar exchange-rates-sample-*.jar extract

FROM eclipse-temurin:21-jre

COPY --from=builder /build/target/layers/dependencies/ ./
COPY --from=builder /build/target/layers/snapshot-dependencies/ ./
COPY --from=builder /build/target/layers/spring-boot-loader/ ./
COPY --from=builder /build/target/layers/application/ ./

EXPOSE 8080

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.launch.JarLauncher"]
