FROM eclipse-temurin:24-jre AS builder

COPY target/exchange-rates-sample-*.jar app.jar

RUN java -XX:AOTMode=record -XX:AOTConfiguration=app.aotconf -Dspring.context.exit=onRefresh -jar app.jar
RUN java -XX:AOTMode=create -XX:AOTConfiguration=app.aotconf -XX:AOTCache=app.aot -jar app.jar \
      && rm app.aotconf

FROM eclipse-temurin:24-jre

WORKDIR /app

COPY --from=builder app.jar app.jar
COPY --from=builder app.aot app.aot

EXPOSE 8080

ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
