FROM maven:3.9-eclipse-temurin-24 AS builder

COPY . /build

WORKDIR /build

RUN --mount=type=cache,target=/root/.m2 mvn clean install

RUN mkdir target/layers \
    && cp target/exchange-rates-sample-*.jar target/layers

WORKDIR /build/target/layers

RUN java -Djarmode=layertools -jar exchange-rates-sample-*.jar extract

FROM eclipse-temurin:24-jre AS aot-cache

COPY --from=builder /build/target/layers/dependencies/ ./
COPY --from=builder /build/target/layers/snapshot-dependencies/ ./
COPY --from=builder /build/target/layers/spring-boot-loader/ ./
COPY --from=builder /build/target/layers/application/ ./

RUN java -XX:AOTMode=record -XX:AOTConfiguration=app.aotconf -Dspring.context.exit=onRefresh -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loader.launch.JarLauncher
RUN java -XX:AOTMode=create -XX:AOTConfiguration=app.aotconf -XX:AOTCache=app.aot -Djava.security.egd=file:/dev/./urandom org.springframework.boot.loader.launch.JarLauncher \
      && rm app.aotconf

FROM eclipse-temurin:24-jre

COPY --from=builder /build/target/layers/dependencies/ ./
COPY --from=builder /build/target/layers/snapshot-dependencies/ ./
COPY --from=builder /build/target/layers/spring-boot-loader/ ./
COPY --from=builder /build/target/layers/application/ ./

COPY --from=aot-cache app.aot ./app.aot

EXPOSE 8080

ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.launch.JarLauncher"]
